- hosts: &swarm_initiator manager[0]
  user: root
  vars:
    - domains: arcade.joellefkowitz.co.uk
  roles:
    - joellefkowitz.swarmroles.swarm_initiator
    - joellefkowitz.swarmroles.certbot

- hosts: manager
  user: root
  vars:
    - docker_username: joellefkowitz
  vars_files: vars.yml
  pre_tasks: &register_swarm_initiator
    - name: Fetch the swarm initiator host
      set_fact:
        swarm_initiator: "{{groups['manager'][0]}}"
  roles:
    - role: joellefkowitz.swarmroles.swarm_manager
      swarm_join_addr: "{{ hostvars[swarm_initiator]['swarm_join_addr'] }}"
      swarm_manager_token: "{{ hostvars[swarm_initiator]['swarm_manager_token'] }}"

- hosts: worker
  user: root
  pre_tasks: *register_swarm_initiator
  roles:
    - role: joellefkowitz.swarmroles.swarm_worker
      swarm_join_addr: "{{ hostvars[swarm_initiator]['swarm_join_addr'] }}"
      swarm_worker_token: "{{ hostvars[swarm_initiator]['swarm_worker_token'] }}"

- hosts: *swarm_initiator
  user: root
  vars:
    - stack_name: prod
    - compose_file: docker-compose.yml
  vars_files: vars.yml
  roles:
    - joellefkowitz.swarmroles.stack_deployer
